#!/usr/bin/env python3
"""
roomctl — the writers' room compiler.

Reads the Obsidian vault, resolves every [[wikilink]] to its canon note, and
emits one handoff package per episode: a prompt file per 10-second clip plus a
manifest.json describing authorial intent.

The room is model-agnostic on purpose. Nothing here knows which video model runs
downstream, what its parameters are called, or how it dialects a prompt — that is
the video engineering agent's half of the seam. See 00-System/Handoff-Contract.md.

    tools/roomctl.py lint                     # validate the whole network
    tools/roomctl.py build                    # compile every episode, every channel
    tools/roomctl.py build --channel nightshift
    tools/roomctl.py build ep-001-a-single-egg
    tools/roomctl.py new channel "Second Channel Name"
    tools/roomctl.py new episode "Closing Time" --channel nightshift
    tools/roomctl.py ls

Inheritance runs Network → Channel → Series → Episode → Shot. Each layer may
tighten what it inherits; none may contradict it.

Writers do not edit this file. They edit notes.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import unicodedata
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit("roomctl needs PyYAML.  pip install pyyaml")

VAULT = Path(__file__).resolve().parent.parent
BUILD = VAULT / "_build"
TEMPLATES = VAULT / "90-Templates"

FRONTMATTER = re.compile(r"\A---\r?\n(.*?)\r?\n---\r?\n?(.*)\Z", re.S)
WIKILINK = re.compile(r"\[\[([^\]|#]+?)(?:#[^\]|]+)?(?:\|[^\]]+)?\]\]")

# Slot order is the contract. Video models weight early tokens more heavily,
# so format and style land before the free-written beat. See 00-System/Prompt-Grammar.md.
SLOTS = ("format", "style", "cast", "setting", "action", "camera", "dialogue", "audio", "continuity")

# Fallbacks only. The network note is the authority; see 05-Network/Network.md.
MAX_SHOT_SECONDS = 12
CLIPS_PER_POST = (3, 5)

# Look keys, in the order they are concatenated into the STYLE slot.
LOOK_KEYS = ("film", "lens", "lighting", "palette", "grade", "texture")


# ─────────────────────────────────────────────────────────── notes ──


@dataclass
class Note:
    path: Path
    meta: dict
    body: str

    @property
    def stem(self) -> str:
        return self.path.stem

    @property
    def id(self) -> str:
        return str(self.meta.get("id") or slugify(self.stem))

    @property
    def type(self) -> str:
        return str(self.meta.get("type", "note"))

    @property
    def title(self) -> str:
        return str(self.meta.get("title") or self.stem)

    def rel(self) -> str:
        return str(self.path.relative_to(VAULT))


def slugify(text: str) -> str:
    text = unicodedata.normalize("NFKD", str(text)).encode("ascii", "ignore").decode()
    text = re.sub(r"[^\w\s-]", "", text).strip().lower()
    return re.sub(r"[\s_-]+", "-", text)


def parse_note(path: Path) -> Note | None:
    raw = path.read_text(encoding="utf-8")
    match = FRONTMATTER.match(raw)
    if not match:
        return None
    try:
        meta = yaml.safe_load(match.group(1)) or {}
    except yaml.YAMLError as exc:
        raise SystemExit(f"{path.relative_to(VAULT)}: bad frontmatter — {exc}")
    if not isinstance(meta, dict):
        return None
    return Note(path=path, meta=meta, body=match.group(2))


class Index:
    """Every note in the vault, addressable the way Obsidian addresses them."""

    def __init__(self) -> None:
        self.notes: list[Note] = []
        self.by_key: dict[str, list[Note]] = {}
        for path in sorted(VAULT.rglob("*.md")):
            relative = path.relative_to(VAULT)
            # Templates hold {{placeholders}} that aren't valid YAML, and dot- and
            # underscore-prefixed paths are Obsidian's and the build's business.
            if relative.parts[0] == TEMPLATES.name:
                continue
            if any(part.startswith((".", "_")) for part in relative.parts):
                continue
            note = parse_note(path)
            if note is None:
                continue
            self.notes.append(note)
            for key in {note.stem.lower(), note.id.lower(), note.title.lower()}:
                self.by_key.setdefault(key, []).append(note)

    def of_type(self, *types: str) -> list[Note]:
        return [n for n in self.notes if n.type in types]

    def resolve(self, ref: str | None, near: Path | None = None) -> Note | None:
        """Resolve a [[wikilink]]. Channels are allowed to share note names — each
        one keeps its own Voice-and-Tone — so the nearest candidate in the tree
        wins, and only a link with no local match reaches across the network."""
        if not ref:
            return None
        match = WIKILINK.search(str(ref))
        key = (match.group(1) if match else str(ref)).strip().lower()
        candidates = self.by_key.get(key, [])
        if not candidates:
            return None
        if len(candidates) == 1 or near is None:
            return candidates[0]

        def shared_depth(note: Note) -> int:
            a, b = note.path.parts, near.parts
            depth = 0
            while depth < min(len(a), len(b)) and a[depth] == b[depth]:
                depth += 1
            return depth

        return max(candidates, key=shared_depth)


def as_list(value) -> list:
    if value is None:
        return []
    return list(value) if isinstance(value, (list, tuple)) else [value]


def sentence(text) -> str:
    """Normalize a fragment into one clause the model can read as prose."""
    text = re.sub(r"\s+", " ", str(text or "")).strip()
    if not text:
        return ""
    return text if text[-1] in ".!?\"'" else text + "."


def plural(count: int, noun: str) -> str:
    return f"{count} {noun}" + ("" if count == 1 else "s")


def tidy(text):
    """Collapse a folded scalar to one clean line, leaving punctuation alone."""
    if not isinstance(text, str):
        return text
    return re.sub(r"\s+", " ", text).strip()


def clause(text) -> str:
    """A fragment with its whitespace collapsed and its full stop removed, so it
    can be embedded mid-sentence. YAML folded scalars arrive with a trailing
    newline, which is what makes the naive version produce ' . , holding'."""
    return re.sub(r"\s+", " ", str(text or "")).strip().rstrip(".").strip()


def join(parts) -> str:
    return " ".join(p for p in (sentence(x) for x in parts) if p)


# ──────────────────────────────────────────────────────── problems ──


@dataclass
class Report:
    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    def error(self, where: str, msg: str) -> None:
        self.errors.append(f"{where}: {msg}")

    def warn(self, where: str, msg: str) -> None:
        self.warnings.append(f"{where}: {msg}")

    def print(self) -> None:
        for line in self.errors:
            print(f"  ERROR    {line}")
        for line in self.warnings:
            print(f"  warning  {line}")


# ───────────────────────────────────────────────────────── compile ──


@dataclass
class Chain:
    """The inheritance chain standing behind one episode."""

    network: Note | None
    channel: Note
    series: Note | None
    episode: Note

    @property
    def look(self) -> dict:
        """Network defaults, tightened by the channel. Never contradicted."""
        merged = dict((self.network.meta.get("look") or {}) if self.network else {})
        merged.update(self.channel.meta.get("look") or {})
        return merged

    @property
    def layers(self) -> list[Note]:
        return [n for n in (self.network, self.channel, self.series) if n is not None]


def chain_for(index: Index, episode: Note, report: Report) -> Chain | None:
    """An episode names a series or a channel; everything above resolves from there."""
    where = episode.rel()
    near = episode.path
    series = index.resolve(episode.meta.get("series"), near)
    channel = index.resolve(episode.meta.get("channel") or episode.meta.get("brand"), near)
    if channel is None and series is not None:
        channel = index.resolve(series.meta.get("channel") or series.meta.get("brand"), near)
    if channel is None:
        report.error(where, "no `channel:` and no series that names one")
        return None

    network = index.resolve(channel.meta.get("network"), near)
    if network is None:
        networks = index.of_type("network")
        if len(networks) == 1:
            network = networks[0]
        elif networks:
            report.error(channel.rel(), "several networks exist; the channel must name its `network:`")
    return Chain(network=network, channel=channel, series=series, episode=episode)


def style_block(chain: Chain) -> str:
    look = chain.look
    parts = [look.get(k) for k in LOOK_KEYS]
    if chain.series is not None:
        parts.append((chain.series.meta.get("look") or {}).get("override"))
    return join(parts)


def format_block(chain: Chain, seconds) -> str:
    look = chain.look
    return (
        f"{seconds}-second single continuous shot, "
        f"{look.get('aspect', '9:16 vertical')}, {look.get('fps', '24 fps')}, no cuts"
    )


def negatives(chain: Chain, notes: list[Note], shot: dict) -> list[str]:
    out: list[str] = []
    for source in (*chain.layers, *notes):
        out += as_list(source.meta.get("negative"))
    out += as_list(shot.get("negative"))
    seen, deduped = set(), []
    for item in out:
        key = str(item).strip().lower()
        if key and key not in seen:
            seen.add(key)
            deduped.append(str(item).strip())
    return deduped


def dialogue_block(index: Index, shot: dict, report: Report, where: str, near: Path) -> str:
    lines = []
    for entry in as_list(shot.get("dialogue")):
        if isinstance(entry, str):
            lines.append(f'Someone says: "{entry}"')
            continue
        who = index.resolve(entry.get("who"), near)
        name = (who.title if who else entry.get("who") or "Off-screen").upper()
        delivery = str(entry.get("delivery") or (who.meta.get("delivery") if who else "") or "").strip()
        text = str(entry.get("line", "")).strip()
        if not text:
            report.warn(where, "a dialogue entry has no line")
            continue
        lines.append(f'{name} says, {delivery}: "{text}"' if delivery else f'{name} says: "{text}"')
    return " ".join(lines)


def compile_shot(index: Index, chain: Chain, shot: dict, number: int,
                 previous: dict | None, report: Report) -> dict:
    episode = chain.episode
    where = f"{episode.rel()} shot {number}"
    limits = (chain.network.meta.get("format") or {}) if chain.network else {}
    max_seconds = limits.get("max_clip_seconds", MAX_SHOT_SECONDS)
    seconds = shot.get("duration", limits.get("clip_seconds", 10))
    if not isinstance(seconds, (int, float)) or not 1 <= seconds <= max_seconds:
        report.error(where, f"duration {seconds!r} is not 1–{max_seconds} seconds")
        seconds = limits.get("clip_seconds", 10)

    cast: list[Note] = []
    for ref in as_list(shot.get("cast")):
        note = index.resolve(ref, episode.path)
        if note is None:
            report.error(where, f"cast {ref!r} does not resolve to a canon note")
            continue
        if not note.meta.get("lock"):
            report.error(note.rel(), "character has no `lock:` — nothing to hold continuity with")
        home = index.resolve(note.meta.get("channel") or note.meta.get("brand"), note.path)
        if home is not None and home.id != chain.channel.id:
            # Not an error — crossovers are a network's whole advantage. But they
            # should be deliberate, so they're never silent.
            report.warn(where, f"crossover: {note.title} belongs to {home.title}")
        cast.append(note)

    props: list[Note] = []
    for ref in as_list(shot.get("props")):
        note = index.resolve(ref, episode.path)
        if note is None:
            report.error(where, f"prop {ref!r} does not resolve to a canon note")
            continue
        props.append(note)

    location = index.resolve(shot.get("location") or episode.meta.get("location"), episode.path)
    if shot.get("location") and location is None:
        report.error(where, f"location {shot['location']!r} does not resolve to a canon note")
    if location is None:
        report.warn(where, "no location — the model will invent one, and it will differ next clip")

    if not shot.get("action"):
        report.error(where, "no `action:` — this is the one field a writer must write")
    if not shot.get("camera"):
        report.warn(where, "no `camera:` — falling back to the channel's default move")

    # Continuity: a shot opens where the last one ended, unless it says otherwise.
    opens = shot.get("first_frame")
    if not opens and previous is not None:
        opens = previous.get("last_frame")
    ends = shot.get("last_frame")
    if not ends and number < 99:
        report.warn(where, "no `last_frame:` — the next clip has nothing to match to")

    setting_parts = [location.meta.get("lock") if location else None]
    setting_parts += [p.meta.get("lock") for p in props]
    setting_parts.append(shot.get("setting_note"))

    continuity_parts = []
    if opens:
        continuity_parts.append(f"The clip opens on {clause(opens)}")
    if ends:
        continuity_parts.append(f"The clip ends on {clause(ends)}, holding for the cut")

    blocks = {
        "format": format_block(chain, seconds),
        "style": style_block(chain),
        "cast": join(n.meta.get("lock") for n in cast),
        "setting": join(setting_parts),
        "action": sentence(shot.get("action")),
        "camera": sentence(shot.get("camera") or chain.look.get("default_camera")),
        "dialogue": dialogue_block(index, shot, report, where, episode.path),
        "audio": join([shot.get("audio"), (chain.channel.meta.get("audio") or {}).get("bed")]),
        "continuity": join(continuity_parts),
    }

    avoid = negatives(chain, cast + props + ([location] if location else []), shot)

    prose = "\n\n".join(blocks[s] for s in SLOTS if blocks[s])
    labeled_lines = [f"[{s.upper()}] {blocks[s]}" for s in SLOTS if blocks[s]]
    if avoid:
        labeled_lines.append("[AVOID] " + ", ".join(avoid))

    return {
        "shot": number,
        "id": f"{episode.id}-{number:02d}",
        "beat": shot.get("beat", ""),
        "duration_seconds": seconds,
        "cast": [n.title for n in cast],
        "location": location.title if location else None,
        "props": [n.title for n in props],
        "prompt": prose,
        "prompt_labeled": "\n\n".join(labeled_lines),
        "negative_prompt": ", ".join(avoid),
        "blocks": blocks,
        "last_frame": clause(ends) or None,
    }


def compile_episode(index: Index, episode: Note, report: Report) -> dict | None:
    where = episode.rel()
    chain = chain_for(index, episode, report)
    if chain is None:
        return None

    limits = (chain.network.meta.get("format") or {}) if chain.network else {}
    for key in as_list(limits.get("channels_must_define")):
        value = chain.look.get(key) or chain.channel.meta.get(key)
        if not value:
            report.error(chain.channel.rel(), f"the network requires every channel to define `{key}`")
        elif "TODO" in str(value):
            # Scaffold prose is worse than nothing — it compiles, and it ships.
            report.error(chain.channel.rel(), f"`look.{key}` is still scaffold text")

    shots = as_list(episode.meta.get("shots"))
    if not shots:
        report.error(where, "no `shots:` — an episode is a handful of clips")
        return None
    low, high = as_list(limits.get("clips_per_post")) or CLIPS_PER_POST
    if not low <= len(shots) <= high:
        report.warn(where, f"{len(shots)} clips; a post holds {low}–{high}")

    compiled, previous = [], None
    for number, shot in enumerate(shots, start=1):
        if not isinstance(shot, dict):
            report.error(where, f"shot {number} is not a mapping")
            continue
        compiled.append(compile_shot(index, chain, shot, number, previous, report))
        previous = shot

    total = sum(c["duration_seconds"] for c in compiled)
    ceiling = limits.get("max_post_seconds", 60)
    if total > ceiling:
        report.warn(where, f"{total}s total — the format tops out at {ceiling}s")

    post = {k: tidy(v) for k, v in (episode.meta.get("post") or {}).items()}
    if not post.get("caption"):
        report.warn(where, "no `post.caption:` — the clip ships without words")

    return {
        "handoff_schema": "writers-room/1",
        "network": chain.network.meta.get("name") if chain.network else None,
        "channel": chain.channel.meta.get("name") or chain.channel.title,
        "channel_id": chain.channel.id,
        "series": chain.series.title if chain.series else None,
        "episode": episode.id,
        "title": episode.title,
        "premise": tidy(episode.meta.get("premise")),
        "hook": tidy(episode.meta.get("hook")),
        "total_seconds": total,
        "aspect": chain.look.get("aspect", "9:16 vertical"),
        "fps": chain.look.get("fps"),
        "post": post,
        "shots": compiled,
        "compiled": date.today().isoformat(),
        "source": where,
    }


# ─────────────────────────────────────────────────────────── write ──


def contact_sheet(pack: dict) -> str:
    lines = [
        f"# {pack['title']}",
        "",
        f"**{pack['channel']}**"
        + (f" · {pack['series']}" if pack["series"] else "")
        + f" · {len(pack['shots'])} clips · {pack['total_seconds']}s · {pack['aspect']}",
        "",
        f"> {pack['hook']}" if pack.get("hook") else "",
        "",
        "Compiled from `" + pack["source"] + "`. Do not edit — edit the episode note and rebuild.",
        "",
    ]
    for shot in pack["shots"]:
        lines += [
            "---",
            "",
            f"## {shot['shot']:02d} · {shot['beat'] or 'shot'} · {shot['duration_seconds']}s",
            "",
            f"*{', '.join(shot['cast']) or 'no cast'}"
            + (f" — {shot['location']}*" if shot["location"] else "*"),
            "",
            "```",
            shot["prompt"],
            "```",
            "",
        ]
        if shot["negative_prompt"]:
            lines += [f"**Avoid:** {shot['negative_prompt']}", ""]
    post = pack.get("post") or {}
    if post:
        lines += ["---", "", "## Post", ""]
        if post.get("caption"):
            lines += [post["caption"], ""]
        if post.get("hashtags"):
            lines += [" ".join(f"#{h.lstrip('#')}" for h in as_list(post["hashtags"])), ""]
        if post.get("sound"):
            lines += [f"**Sound:** {post['sound']}", ""]
    return "\n".join(lines).replace("\n\n\n", "\n\n")


def write_pack(pack: dict, labeled: bool) -> Path:
    out = BUILD / pack["channel_id"] / pack["episode"]
    out.mkdir(parents=True, exist_ok=True)
    for shot in pack["shots"]:
        text = shot["prompt_labeled"] if labeled else shot["prompt"]
        if not labeled and shot["negative_prompt"]:
            text += "\n\nAvoid: " + shot["negative_prompt"]
        (out / f"shot-{shot['shot']:02d}.txt").write_text(text + "\n", encoding="utf-8")
    (out / "manifest.json").write_text(json.dumps(pack, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    (out / "CONTACT-SHEET.md").write_text(contact_sheet(pack), encoding="utf-8")
    return out


# ──────────────────────────────────────────────────────── commands ──


def channels(index: Index) -> list[Note]:
    return sorted(index.of_type("channel"), key=lambda n: n.id)


def pick_channel(index: Index, wanted: str | None) -> Note | None:
    found = channels(index)
    if wanted:
        for note in found:
            if wanted.lower() in (note.id, note.stem.lower(), note.title.lower()):
                return note
        print(f"No channel matches {wanted!r}.  Known: {', '.join(n.id for n in found) or 'none'}")
        return None
    if len(found) == 1:
        return found[0]
    print("Several channels exist — say which with --channel: " + ", ".join(n.id for n in found))
    return None


def cmd_lint(args) -> int:
    index = Index()
    report = Report()
    if not index.of_type("network"):
        report.warn("05-Network/", "no network note — channels have nothing to inherit from")
    episodes = index.of_type("episode")
    if not episodes:
        print('No episodes yet.  tools/roomctl.py new episode "Title"')
    for episode in episodes:
        compile_episode(index, episode, report)
    for note in index.of_type("character"):
        if not note.meta.get("lock"):
            report.error(note.rel(), "character has no `lock:`")
    report.print()
    print(f"\n{plural(len(channels(index)), 'channel')} · {plural(len(index.notes), 'note')} · "
          f"{plural(len(episodes), 'episode')} · {plural(len(report.errors), 'error')} · "
          f"{plural(len(report.warnings), 'warning')}")
    return 1 if report.errors else 0


def cmd_build(args) -> int:
    index = Index()
    report = Report()
    episodes = index.of_type("episode")
    if args.channel:
        channel = pick_channel(index, args.channel)
        if channel is None:
            return 1
        episodes = [e for e in episodes
                    if (c := chain_for(index, e, Report())) and c.channel.id == channel.id]
    if args.episode:
        episodes = [e for e in episodes if args.episode in (e.id, e.stem)]
        if not episodes:
            print(f"No episode matches {args.episode!r}")
            return 1
    built = 0
    for episode in episodes:
        pack = compile_episode(index, episode, report)
        if pack is None:
            continue
        out = write_pack(pack, args.labeled)
        built += 1
        print(f"  {pack['channel_id']:<14} {pack['episode']:<26} "
              f"{len(pack['shots'])} clips → {out.relative_to(VAULT)}/")
    report.print()
    print(f"\nbuilt {plural(built, 'episode')} · {plural(len(report.errors), 'error')} · "
          f"{plural(len(report.warnings), 'warning')}")
    return 1 if report.errors else 0


def new_channel(index: Index, name: str) -> int:
    """A channel is a folder, not a file — scaffold it whole from 90-Templates/_Channel."""
    scaffold = TEMPLATES / "_Channel"
    target = VAULT / "10-Channels" / name
    if target.exists():
        print(f"{target.relative_to(VAULT)} already exists")
        return 1
    network = (index.of_type("network") or [None])[0]
    substitutions = {
        "{{id}}": slugify(name),
        "{{title}}": name,
        "{{date}}": date.today().isoformat(),
        "{{network}}": network.title if network else "Network",
    }
    for source in sorted(scaffold.rglob("*")):
        relative = source.relative_to(scaffold)
        # The channel note is a folder note — it takes the channel's own name.
        if relative.name == "Channel.md":
            relative = relative.with_name(f"{name}.md")
        destination = target / relative
        if source.is_dir():
            destination.mkdir(parents=True, exist_ok=True)
            continue
        text = source.read_text(encoding="utf-8")
        for token, value in substitutions.items():
            text = text.replace(token, value)
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(text, encoding="utf-8")
    print(f"created {target.relative_to(VAULT)}/ — start with Channel.md, then Canon/")
    return 0


def cmd_new(args) -> int:
    index = Index()
    kind, name = args.kind, args.name
    if kind == "channel":
        return new_channel(index, name)

    channel = pick_channel(index, args.channel)
    if channel is None:
        return 1
    root = channel.path.parent
    template = TEMPLATES / f"{kind.capitalize()}.md"
    if not template.exists():
        print(f"No template for {kind!r} in 90-Templates/")
        return 1

    folders = {
        "episode": root / "Episodes",
        "series": root / "Series",
        "character": root / "Canon/Characters",
        "location": root / "Canon/Locations",
        "prop": root / "Canon/Props",
    }
    folder = folders[kind]
    folder.mkdir(parents=True, exist_ok=True)

    slug = slugify(name)
    if kind == "episode":
        slug = f"ep-{len(list(folder.glob('ep-*.md'))) + 1:03d}-{slug}"
        filename = f"{slug}.md"
    else:
        filename = f"{name}.md"

    target = folder / filename
    if target.exists():
        print(f"{target.relative_to(VAULT)} already exists")
        return 1
    text = (template.read_text(encoding="utf-8")
            .replace("{{id}}", slug)
            .replace("{{title}}", name)
            .replace("{{date}}", date.today().isoformat())
            .replace("{{channel}}", channel.title))
    target.write_text(text, encoding="utf-8")
    print(f"created {target.relative_to(VAULT)}")
    return 0


def cmd_ls(args) -> int:
    index = Index()
    for network in index.of_type("network"):
        print(f"\n{(network.meta.get('name') or network.title).upper()}")
    for channel in channels(index):
        root = channel.path.parent
        print(f"\n  ▸ {channel.meta.get('name') or channel.title}  ({channel.id})")
        for kind, label in (("series", "series"), ("episode", "episodes"),
                            ("character", "characters"), ("location", "locations"), ("prop", "props")):
            notes = [n for n in index.of_type(kind) if root in n.path.parents]
            if notes:
                print(f"      {label:<12} " + ", ".join(n.title for n in notes))
    orphans = [n for n in index.of_type("episode", "character", "location", "prop", "series")
               if not any(c.path.parent in n.path.parents for c in channels(index))]
    if orphans:
        print("\n  unfiled (outside any channel)")
        for note in orphans:
            print(f"      {note.rel()}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(prog="roomctl", description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    subs = parser.add_subparsers(dest="command", required=True)

    subs.add_parser("lint", help="validate every note and episode").set_defaults(fn=cmd_lint)

    build = subs.add_parser("build", help="compile episodes into _build/")
    build.add_argument("episode", nargs="?", help="episode id; omit to build all")
    build.add_argument("--channel", help="restrict to one channel")
    build.add_argument("--labeled", action="store_true", help="emit [SLOT]-tagged prompts")
    build.set_defaults(fn=cmd_build)

    new = subs.add_parser("new", help="create a note, or scaffold a whole channel")
    new.add_argument("kind", choices=["channel", "episode", "character", "location", "prop", "series"])
    new.add_argument("name")
    new.add_argument("--channel", help="which channel it belongs to (optional if there is only one)")
    new.set_defaults(fn=cmd_new)

    subs.add_parser("ls", help="show the network, its channels, and their canon").set_defaults(fn=cmd_ls)

    args = parser.parse_args()
    return args.fn(args)


if __name__ == "__main__":
    sys.exit(main())
