#!/usr/bin/env python3
"""
roomctl — the writers' room compiler.

Reads the Obsidian vault, resolves every [[wikilink]] to its canon note, and
emits one handoff package per episode: a prompt file per 10-second clip plus a
manifest.json describing authorial intent.

The room is model-agnostic on purpose. Nothing here knows which video model runs
downstream, what its parameters are called, or how it dialects a prompt — that is
the video engineering agent's half of the seam. See 00-System/Handoff-Contract.md.

    tools/roomctl.py lint                    # validate the whole vault
    tools/roomctl.py build                   # compile every episode
    tools/roomctl.py build ep-001-closing    # compile one
    tools/roomctl.py new episode "Closing Time"
    tools/roomctl.py new character "Vic"
    tools/roomctl.py ls

Writers do not edit this file. They edit notes.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import unicodedata
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit("roomctl needs PyYAML.  pip install pyyaml")

VAULT = Path(__file__).resolve().parent.parent
BUILD = VAULT / "_build"
TEMPLATES = VAULT / "90-Templates"

FRONTMATTER = re.compile(r"\A---\r?\n(.*?)\r?\n---\r?\n?(.*)\Z", re.S)
WIKILINK = re.compile(r"\[\[([^\]|#]+?)(?:#[^\]|]+)?(?:\|[^\]]+)?\]\]")

# Slot order is the contract. Video models weight early tokens more heavily,
# so format and style land before the free-written beat. See 00-System/Prompt-Grammar.md.
SLOTS = ("format", "style", "cast", "setting", "action", "camera", "dialogue", "audio", "continuity")

MAX_SHOT_SECONDS = 12
CLIPS_PER_POST = (3, 5)


# ─────────────────────────────────────────────────────────── notes ──


@dataclass
class Note:
    path: Path
    meta: dict
    body: str

    @property
    def stem(self) -> str:
        return self.path.stem

    @property
    def id(self) -> str:
        return str(self.meta.get("id") or slugify(self.stem))

    @property
    def type(self) -> str:
        return str(self.meta.get("type", "note"))

    @property
    def title(self) -> str:
        return str(self.meta.get("title") or self.stem)

    def rel(self) -> str:
        return str(self.path.relative_to(VAULT))


def slugify(text: str) -> str:
    text = unicodedata.normalize("NFKD", str(text)).encode("ascii", "ignore").decode()
    text = re.sub(r"[^\w\s-]", "", text).strip().lower()
    return re.sub(r"[\s_-]+", "-", text)


def parse_note(path: Path) -> Note | None:
    raw = path.read_text(encoding="utf-8")
    match = FRONTMATTER.match(raw)
    if not match:
        return None
    try:
        meta = yaml.safe_load(match.group(1)) or {}
    except yaml.YAMLError as exc:
        raise SystemExit(f"{path.relative_to(VAULT)}: bad frontmatter — {exc}")
    if not isinstance(meta, dict):
        return None
    return Note(path=path, meta=meta, body=match.group(2))


class Index:
    """Every note in the vault, addressable the way Obsidian addresses them."""

    def __init__(self) -> None:
        self.notes: list[Note] = []
        self.by_key: dict[str, Note] = {}
        for path in sorted(VAULT.rglob("*.md")):
            if any(part.startswith((".", "_")) for part in path.relative_to(VAULT).parts):
                continue
            note = parse_note(path)
            if note is None:
                continue
            self.notes.append(note)
            for key in {note.stem.lower(), note.id.lower(), note.title.lower()}:
                self.by_key.setdefault(key, note)

    def of_type(self, *types: str) -> list[Note]:
        return [n for n in self.notes if n.type in types]

    def resolve(self, ref: str | None) -> Note | None:
        if not ref:
            return None
        match = WIKILINK.search(str(ref))
        key = (match.group(1) if match else str(ref)).strip().lower()
        return self.by_key.get(key)


def as_list(value) -> list:
    if value is None:
        return []
    return list(value) if isinstance(value, (list, tuple)) else [value]


def sentence(text) -> str:
    """Normalize a fragment into one clause the model can read as prose."""
    text = re.sub(r"\s+", " ", str(text or "")).strip()
    if not text:
        return ""
    return text if text[-1] in ".!?\"'" else text + "."


def join(parts) -> str:
    return " ".join(p for p in (sentence(x) for x in parts) if p)


# ──────────────────────────────────────────────────────── problems ──


@dataclass
class Report:
    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    def error(self, where: str, msg: str) -> None:
        self.errors.append(f"{where}: {msg}")

    def warn(self, where: str, msg: str) -> None:
        self.warnings.append(f"{where}: {msg}")

    def print(self) -> None:
        for line in self.errors:
            print(f"  ERROR    {line}")
        for line in self.warnings:
            print(f"  warning  {line}")


# ───────────────────────────────────────────────────────── compile ──


def brand_for(index: Index, episode: Note, report: Report) -> Note | None:
    """An episode inherits its brand directly, or through its series."""
    where = episode.rel()
    brand = index.resolve(episode.meta.get("brand"))
    if brand is None:
        series = index.resolve(episode.meta.get("series"))
        if series is None:
            report.error(where, "no brand and no series to inherit one from")
            return None
        brand = index.resolve(series.meta.get("brand"))
        if brand is None:
            report.error(series.rel(), f"series has no resolvable brand (needed by {episode.id})")
            return None
    return brand


def style_block(brand: Note, series: Note | None) -> str:
    look = brand.meta.get("look") or {}
    parts = [look.get(k) for k in ("film", "lens", "lighting", "palette", "grade", "texture")]
    if series is not None:
        parts.append((series.meta.get("look") or {}).get("override"))
    return join(parts)


def format_block(brand: Note, seconds) -> str:
    look = brand.meta.get("look") or {}
    return (
        f"{seconds}-second single continuous shot, "
        f"{look.get('aspect', '9:16 vertical')}, {look.get('fps', '24 fps')}, no cuts"
    )


def negatives(brand: Note, series: Note | None, notes: list[Note], shot: dict) -> list[str]:
    out: list[str] = []
    for source in (brand, series, *notes):
        if source is not None:
            out += as_list(source.meta.get("negative"))
    out += as_list(shot.get("negative"))
    seen, deduped = set(), []
    for item in out:
        key = str(item).strip().lower()
        if key and key not in seen:
            seen.add(key)
            deduped.append(str(item).strip())
    return deduped


def dialogue_block(index: Index, shot: dict, report: Report, where: str) -> str:
    lines = []
    for entry in as_list(shot.get("dialogue")):
        if isinstance(entry, str):
            lines.append(f'Someone says: "{entry}"')
            continue
        who = index.resolve(entry.get("who"))
        name = (who.title if who else entry.get("who") or "Off-screen").upper()
        delivery = str(entry.get("delivery") or (who.meta.get("delivery") if who else "") or "").strip()
        text = str(entry.get("line", "")).strip()
        if not text:
            report.warn(where, "a dialogue entry has no line")
            continue
        lines.append(f'{name} says, {delivery}: "{text}"' if delivery else f'{name} says: "{text}"')
    return " ".join(lines)


def compile_shot(index: Index, episode: Note, brand: Note, series: Note | None,
                 shot: dict, number: int, previous: dict | None, report: Report) -> dict:
    where = f"{episode.rel()} shot {number}"
    seconds = shot.get("duration", 10)
    if not isinstance(seconds, (int, float)) or not 1 <= seconds <= MAX_SHOT_SECONDS:
        report.error(where, f"duration {seconds!r} is not 1–{MAX_SHOT_SECONDS} seconds")
        seconds = 10

    cast: list[Note] = []
    for ref in as_list(shot.get("cast")):
        note = index.resolve(ref)
        if note is None:
            report.error(where, f"cast {ref!r} does not resolve to a canon note")
            continue
        if not note.meta.get("lock"):
            report.error(note.rel(), "character has no `lock:` — nothing to hold continuity with")
        cast.append(note)

    props: list[Note] = []
    for ref in as_list(shot.get("props")):
        note = index.resolve(ref)
        if note is None:
            report.error(where, f"prop {ref!r} does not resolve to a canon note")
            continue
        props.append(note)

    location = index.resolve(shot.get("location") or episode.meta.get("location"))
    if shot.get("location") and location is None:
        report.error(where, f"location {shot['location']!r} does not resolve to a canon note")
    if location is None:
        report.warn(where, "no location — the model will invent one, and it will differ next clip")

    if not shot.get("action"):
        report.error(where, "no `action:` — this is the one field a writer must write")
    if not shot.get("camera"):
        report.warn(where, "no `camera:` — falling back to the brand's default move")

    # Continuity: a shot opens where the last one ended, unless it says otherwise.
    opens = shot.get("first_frame")
    if not opens and previous is not None:
        opens = previous.get("last_frame")
    ends = shot.get("last_frame")
    if not ends and number < 99:
        report.warn(where, "no `last_frame:` — the next clip has nothing to match to")

    setting_parts = [location.meta.get("lock") if location else None]
    setting_parts += [p.meta.get("lock") for p in props]
    setting_parts.append(shot.get("setting_note"))

    continuity_parts = []
    if opens:
        continuity_parts.append(f"The clip opens on {str(opens).rstrip('.')}")
    if ends:
        continuity_parts.append(f"The clip ends on {str(ends).rstrip('.')}, holding for the cut")

    blocks = {
        "format": format_block(brand, seconds),
        "style": style_block(brand, series),
        "cast": join(n.meta.get("lock") for n in cast),
        "setting": join(setting_parts),
        "action": sentence(shot.get("action")),
        "camera": sentence(shot.get("camera") or (brand.meta.get("look") or {}).get("default_camera")),
        "dialogue": dialogue_block(index, shot, report, where),
        "audio": join([shot.get("audio"), (brand.meta.get("audio") or {}).get("bed")]),
        "continuity": join(continuity_parts),
    }

    avoid = negatives(brand, series, cast + props + ([location] if location else []), shot)

    prose = "\n\n".join(blocks[s] for s in SLOTS if blocks[s])
    labeled_lines = [f"[{s.upper()}] {blocks[s]}" for s in SLOTS if blocks[s]]
    if avoid:
        labeled_lines.append("[AVOID] " + ", ".join(avoid))

    return {
        "shot": number,
        "id": f"{episode.id}-{number:02d}",
        "beat": shot.get("beat", ""),
        "duration_seconds": seconds,
        "cast": [n.title for n in cast],
        "location": location.title if location else None,
        "props": [n.title for n in props],
        "prompt": prose,
        "prompt_labeled": "\n\n".join(labeled_lines),
        "negative_prompt": ", ".join(avoid),
        "blocks": blocks,
        "last_frame": ends,
    }


def compile_episode(index: Index, episode: Note, report: Report) -> dict | None:
    where = episode.rel()
    brand = brand_for(index, episode, report)
    if brand is None:
        return None
    series = index.resolve(episode.meta.get("series"))

    shots = as_list(episode.meta.get("shots"))
    if not shots:
        report.error(where, "no `shots:` — an episode is 3–5 clips")
        return None
    low, high = CLIPS_PER_POST
    if not low <= len(shots) <= high:
        report.warn(where, f"{len(shots)} clips; a post holds {low}–{high}")

    compiled, previous = [], None
    for number, shot in enumerate(shots, start=1):
        if not isinstance(shot, dict):
            report.error(where, f"shot {number} is not a mapping")
            continue
        compiled.append(compile_shot(index, episode, brand, series, shot, number, previous, report))
        previous = shot

    total = sum(c["duration_seconds"] for c in compiled)
    if total > 60:
        report.warn(where, f"{total}s total — longer than the format wants")

    post = episode.meta.get("post") or {}
    if not post.get("caption"):
        report.warn(where, "no `post.caption:` — the clip ships without words")

    return {
        "handoff_schema": "writers-room/1",
        "episode": episode.id,
        "title": episode.title,
        "series": series.title if series else None,
        "brand": brand.title,
        "premise": episode.meta.get("premise"),
        "hook": episode.meta.get("hook"),
        "total_seconds": total,
        "aspect": (brand.meta.get("look") or {}).get("aspect", "9:16 vertical"),
        "post": post,
        "shots": compiled,
        "compiled": date.today().isoformat(),
        "source": where,
    }


# ─────────────────────────────────────────────────────────── write ──


def contact_sheet(pack: dict) -> str:
    lines = [
        f"# {pack['title']}",
        "",
        f"**{pack['brand']}**"
        + (f" · {pack['series']}" if pack["series"] else "")
        + f" · {len(pack['shots'])} clips · {pack['total_seconds']}s · {pack['aspect']}",
        "",
        f"> {pack['hook']}" if pack.get("hook") else "",
        "",
        "Compiled from `" + pack["source"] + "`. Do not edit — edit the episode note and rebuild.",
        "",
    ]
    for shot in pack["shots"]:
        lines += [
            "---",
            "",
            f"## {shot['shot']:02d} · {shot['beat'] or 'shot'} · {shot['duration_seconds']}s",
            "",
            f"*{', '.join(shot['cast']) or 'no cast'}"
            + (f" — {shot['location']}*" if shot["location"] else "*"),
            "",
            "```",
            shot["prompt"],
            "```",
            "",
        ]
        if shot["negative_prompt"]:
            lines += [f"**Avoid:** {shot['negative_prompt']}", ""]
    post = pack.get("post") or {}
    if post:
        lines += ["---", "", "## Post", ""]
        if post.get("caption"):
            lines += [post["caption"], ""]
        if post.get("hashtags"):
            lines += [" ".join(f"#{h.lstrip('#')}" for h in as_list(post["hashtags"])), ""]
        if post.get("sound"):
            lines += [f"**Sound:** {post['sound']}", ""]
    return "\n".join(lines).replace("\n\n\n", "\n\n")


def write_pack(pack: dict, labeled: bool) -> Path:
    out = BUILD / pack["episode"]
    out.mkdir(parents=True, exist_ok=True)
    for shot in pack["shots"]:
        text = shot["prompt_labeled"] if labeled else shot["prompt"]
        if not labeled and shot["negative_prompt"]:
            text += "\n\nAvoid: " + shot["negative_prompt"]
        (out / f"shot-{shot['shot']:02d}.txt").write_text(text + "\n", encoding="utf-8")
    (out / "manifest.json").write_text(json.dumps(pack, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    (out / "CONTACT-SHEET.md").write_text(contact_sheet(pack), encoding="utf-8")
    return out


# ──────────────────────────────────────────────────────── commands ──


def cmd_lint(args) -> int:
    index = Index()
    report = Report()
    episodes = index.of_type("episode")
    if not episodes:
        print("No episodes yet.  tools/roomctl.py new episode \"Title\"")
    for episode in episodes:
        compile_episode(index, episode, report)
    for note in index.of_type("character"):
        if not note.meta.get("lock"):
            report.error(note.rel(), "character has no `lock:`")
    report.print()
    print(f"\n{len(index.notes)} notes · {len(episodes)} episodes · "
          f"{len(report.errors)} errors · {len(report.warnings)} warnings")
    return 1 if report.errors else 0


def cmd_build(args) -> int:
    index = Index()
    report = Report()
    episodes = index.of_type("episode")
    if args.episode:
        episodes = [e for e in episodes if args.episode in (e.id, e.stem)]
        if not episodes:
            print(f"No episode matches {args.episode!r}")
            return 1
    built = 0
    for episode in episodes:
        pack = compile_episode(index, episode, report)
        if pack is None:
            continue
        out = write_pack(pack, args.labeled)
        built += 1
        print(f"  {pack['episode']:<28} {len(pack['shots'])} clips → {out.relative_to(VAULT)}/")
    report.print()
    print(f"\nbuilt {built} episode(s) · {len(report.errors)} errors · {len(report.warnings)} warnings")
    return 1 if report.errors else 0


def cmd_new(args) -> int:
    kind, name = args.kind, args.name
    template = TEMPLATES / f"{kind.capitalize()}.md"
    if not template.exists():
        print(f"No template for {kind!r} in 90-Templates/")
        return 1
    folders = {
        "episode": VAULT / "40-Episodes",
        "character": VAULT / "20-Canon/Characters",
        "location": VAULT / "20-Canon/Locations",
        "prop": VAULT / "20-Canon/Props",
        "series": VAULT / "30-Series",
    }
    slug = slugify(name)
    if kind == "episode":
        existing = len(list(folders["episode"].glob("ep-*.md"))) + 1
        slug = f"ep-{existing:03d}-{slug}"
        filename = f"{slug}.md"
    else:
        filename = f"{name}.md"
    target = folders[kind] / filename
    if target.exists():
        print(f"{target.relative_to(VAULT)} already exists")
        return 1
    text = (template.read_text(encoding="utf-8")
            .replace("{{id}}", slug)
            .replace("{{title}}", name)
            .replace("{{date}}", date.today().isoformat()))
    target.write_text(text, encoding="utf-8")
    print(f"created {target.relative_to(VAULT)}")
    return 0


def cmd_ls(args) -> int:
    index = Index()
    for kind in ("brand", "series", "episode", "character", "location", "prop"):
        notes = index.of_type(kind)
        if notes:
            print(f"\n{kind.upper()}  ({len(notes)})")
            for note in notes:
                print(f"  {note.id:<28} {note.rel()}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(prog="roomctl", description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    subs = parser.add_subparsers(dest="command", required=True)

    subs.add_parser("lint", help="validate every note and episode").set_defaults(fn=cmd_lint)

    build = subs.add_parser("build", help="compile episodes into _build/")
    build.add_argument("episode", nargs="?", help="episode id; omit to build all")
    build.add_argument("--labeled", action="store_true", help="emit [SLOT]-tagged prompts")
    build.set_defaults(fn=cmd_build)

    new = subs.add_parser("new", help="create a note from a template")
    new.add_argument("kind", choices=["episode", "character", "location", "prop", "series"])
    new.add_argument("name")
    new.set_defaults(fn=cmd_new)

    subs.add_parser("ls", help="list everything in canon").set_defaults(fn=cmd_ls)

    args = parser.parse_args()
    return args.fn(args)


if __name__ == "__main__":
    sys.exit(main())
